# Projet Python pour la Data Science

_Autrices : Melissa MIGAN, Camille PEYTHIEUX-TALDIR, Romane PLUQUET_.

## Introduction

### Sommaire
[Introduction](#introduction)

[Données](#données)

[Analyse](#analyse)

[Conclusion](#conclusion)

## I. Création et exploration de la base de données principale

Dans cette partie, l'objectif est d'importer les différentes bases données et de les fusionner en une base de données exploitable. Nous utilisons trois bases de données initiales, dont une (data_pop) n'est utilisée que dans un graphique, et ne sera donc pas incluse dans notre base de données principale.

| Nom de la base   | Description                                                                 | Source     | Mode d'extraction |
|-----------------|------------------------------------------------------------------------------|------------|-------------------|
| data_medailles  | Nombre de médailles reportées par la France aux Jeux Olympiques par sport et année. | Wikipedia  | Web scraping      |
| data_licences   | Nombre de licenciés sportifs par fédération, sexe, âge et département.       | ?          | CSV, Parquet      |
| data_pop        | Population départementale en France (recensements de 2016 et 2022).          | Insee      | API               |

On importe les modules pour traiter les données.

In [4]:
%pip install -r requirements.txt

# Modules
import pandas as pd
import numpy as np

# Fonctions
from data import *

Requirement already satisfied: pandas in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from -r requirements.txt (line 1)) (2.3.3)
Requirement already satisfied: numpy in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from -r requirements.txt (line 2)) (2.2.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from pandas->-r requirements.txt (line 1)) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from pandas->-r requirements.txt (line 1)) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from pandas->-r requirements.txt (line 1)) (2025.2)
Requirement already satisfied: six>=1.5 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from python-dateutil>=2.8.2->pandas->-r requirements.txt (line 1)) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

### A. Récupération des données

#### 1. Médailles françaises aux Jeux Olympiques

Nous avons scrappé Wikipedia afin d'obtenir les tableaux des médailles (or, argent bronze) obtenues par la France lors des Jeux Olympiques. Nous avons ensuite gelé les bases scrapées dans un souci de reproductibilité, au cas où la page Wikipédia soit modifiée.

Nous avons ainsi obtenu trois tables : une table renseignant le nombre de médailles d'or obtenues par la France aux Jeux Olympiques, par sport et par année, une table renseignant le nombre de médaille d'argent, et une table renseignant le nombre de médailles de bronze.

Nous avons ensuite nettoyé ces tables, en enlevant les années et sports ne nous intéressant pas, ainsi que les lignes et colonnes vident, en replaçant les cellules vides par des NaN et en transformant le nombre de médailles en float.

In [23]:
data_or = pd.read_csv(f"data/data_medailles/data_or_jo.csv")
data_argent = pd.read_csv(f"data/data_medailles/data_argent_jo.csv")
data_bronze = pd.read_csv(f"data/data_medailles/data_bronze_jo.csv")

data_or_clean = nettoyer_base(data_or)
data_argent_clean = nettoyer_base(data_argent)
data_bronze_clean = nettoyer_base(data_bronze)

data_or_clean.head()
data_argent_clean.head()
data_bronze_clean.head()

        Sport  2024  2020  2016
0     Escrime   2.0   1.0   1.0
1        Judo   6.0   3.0   1.0
2  Athlétisme   0.0   0.0   3.0
3    Cyclisme   3.0   2.0   1.0
4    Natation   2.0   0.0   1.0

Suite à cela, nous avons joint ces trois tables afin d'obtenir la table data.medailles.jo, renseignant le nombre de médailles (toutes couleurs confondues) obtenues par la France aux Jeux Olympiques de 2016, 2020 et 2024.

In [27]:
fusionner_bases(data_or, data_argent, data_bronze).head()

,code_sport,sport,2024_or,2020_or,2016_or,2024_argent,2020_argent,2016_argent,2024_bronze,2020_bronze,2016_bronze,total_medailles_2016,total_medailles_2020,total_medailles_2024
0,ATH,Athlétisme,0.0,0.0,0.0,1.0,1.0,3.0,0.0,0.0,3.0,6.0,1.0,1.0
1,AVI,Aviron,0.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,2.0,2.0,0.0
2,BAD,Badminton,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,BAK,Basket-ball,0.0,0.0,0.0,3.0,1.0,0.0,0.0,1.0,0.0,0.0,2.0,3.0
4,BOX,Boxe,0.0,0.0,2.0,2.0,0.0,2.0,1.0,0.0,2.0,6.0,0.0,3.0

### B. Nettoyage des données