In [1]:
import pandas as pd
import numpy as np

In [2]:
data_2016 = pd.read_parquet("Lics_2016_semidef.parquet")
data_2019 = pd.read_parquet("Lics_2019_def.parquet")

In [12]:
data_2019.head()

,Code année N,Code 2024,Codes 2016-2024,Fédération,Année,Sexe,Age,TrancheAge,GrandeTrancheAge,Région,Département,Licences annuelles
0,101,101,101,Fédération Française d'Athlétisme,2019,F,4,a - de 1 à 4 ans,1 - Enfants (1-13),84 - Auvergne-Rhône-Alpes,01 - Ain,4
1,101,101,101,Fédération Française d'Athlétisme,2019,F,5,b - de 5 à 9 ans,1 - Enfants (1-13),84 - Auvergne-Rhône-Alpes,01 - Ain,2
2,101,101,101,Fédération Française d'Athlétisme,2019,F,6,b - de 5 à 9 ans,1 - Enfants (1-13),84 - Auvergne-Rhône-Alpes,01 - Ain,16
3,101,101,101,Fédération Française d'Athlétisme,2019,F,7,b - de 5 à 9 ans,1 - Enfants (1-13),84 - Auvergne-Rhône-Alpes,01 - Ain,34
4,101,101,101,Fédération Française d'Athlétisme,2019,F,8,b - de 5 à 9 ans,1 - Enfants (1-13),84 - Auvergne-Rhône-Alpes,01 - Ain,38

In [ ]:
data_2019["Licences annuelles"][data_2019["Département"] == "NR - Non réparti"].sum()/data_2019["Licences annuelles"].sum()

In [10]:
data_2016.head()
data_2016["Licences annuelles"][data_2016["Département"] == "NR - Non réparti"].sum()/data_2016["Licences annuelles"].sum()
#4% NR

data_2016["Licences annuelles"][data_2016["Sexe"] == "NR - Non réparti"].sum()/data_2016["Licences annuelles"].sum()

np.float64(0.024266439137779948)

In [ ]:
data_licences = pd.read_parquet("data_licences.parquet")

Empty DataFrame
Columns: [code_2024, code_annee_n, codes_2016_2024, federation, annee, sexe, age, tranche_age, grande_tranche_age, region, departement_long, licences_annuelles, code_sport, code_dep]
Index: []

In [23]:
data_licences_NR = data_licences[data_licences["code_dep"].isna()]
data_licences_NR.head()

,code_2024,code_annee_n,codes_2016_2024,federation,annee,sexe,age,tranche_age,grande_tranche_age,region,departement_long,licences_annuelles,code_sport,code_dep
7237,101,101,101,Fédération Française d'Athlétisme,2016,F,7,b - de 5 à 9 ans,1 - Enfants (1-13),ETR - Etranger,ETR - Etranger,1,ATH,None
7238,101,101,101,Fédération Française d'Athlétisme,2016,F,8,b - de 5 à 9 ans,1 - Enfants (1-13),ETR - Etranger,ETR - Etranger,1,ATH,None
7239,101,101,101,Fédération Française d'Athlétisme,2016,F,9,b - de 5 à 9 ans,1 - Enfants (1-13),ETR - Etranger,ETR - Etranger,1,ATH,None
7240,101,101,101,Fédération Française d'Athlétisme,2016,F,10,c - de 10 à 14 ans,1 - Enfants (1-13),ETR - Etranger,ETR - Etranger,3,ATH,None
7241,101,101,101,Fédération Française d'Athlétisme,2016,F,11,c - de 10 à 14 ans,1 - Enfants (1-13),ETR - Etranger,ETR - Etranger,1,ATH,None

In [22]:
data_licences_NR = data_licences[data_licences["departement_long"] == "NR - Non réparti"]
data_licences_NR["code_dep"].describe()

count       0
unique      0
top       NaN
freq      NaN
Name: code_dep, dtype: object

In [26]:
ratio_total = data_licences_NR["licences_annuelles"].sum()/data_licences["licences_annuelles"].sum()
ratio_2016 = data_licences_NR["licences_annuelles"][data_licences_NR["annee"] == 2016].sum()/data_licences["licences_annuelles"][data_licences["annee"]==2016].sum()
ratio_2017 = data_licences_NR["licences_annuelles"][data_licences_NR["annee"] == 2017].sum()/data_licences["licences_annuelles"][data_licences["annee"]==2017].sum()
ratio_2018 = data_licences_NR["licences_annuelles"][data_licences_NR["annee"] == 2018].sum()/data_licences["licences_annuelles"][data_licences["annee"]==2018].sum()
ratio_2019 = data_licences_NR["licences_annuelles"][data_licences_NR["annee"] == 2019].sum()/data_licences["licences_annuelles"][data_licences["annee"]==2019].sum()
ratio_2020 = data_licences_NR["licences_annuelles"][data_licences_NR["annee"] == 2020].sum()/data_licences["licences_annuelles"][data_licences["annee"]==2020].sum()
ratio_2021 = data_licences_NR["licences_annuelles"][data_licences_NR["annee"] == 2021].sum()/data_licences["licences_annuelles"][data_licences["annee"]==2021].sum()
ratio_2022 = data_licences_NR["licences_annuelles"][data_licences_NR["annee"] == 2022].sum()/data_licences["licences_annuelles"][data_licences["annee"]==2022].sum()
ratio_2023 = data_licences_NR["licences_annuelles"][data_licences_NR["annee"] == 2023].sum()/data_licences["licences_annuelles"][data_licences["annee"]==2023].sum()
ratio_2024 = data_licences_NR["licences_annuelles"][data_licences_NR["annee"] == 2024].sum()/data_licences["licences_annuelles"][data_licences["annee"]==2024].sum()
print(ratio_total, ratio_2016, ratio_2017, ratio_2018, ratio_2019, ratio_2020, ratio_2021, ratio_2022, ratio_2023, ratio_2024)

0.02050121254995247 0.047754801495165165 0.05188193883953035 0.04446957658467501 0.007364960502682509 0.0075636890745688174 0.009129555111448947 0.004951794520341908 0.004698381426709411 0.003986640921565236